name: cvandal
favicon: null
layout_spectrum: 0.19519255124032497
typography_spectrum: 0.9109065947122872
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#04030b'
    - '#e4ddc3'
    - '#254049'
    - '#42665c'
    - '#79957c'
  brandStrength: 0.5
  lightness: 0.6646224996075034
  saturation: 0.5
  rhythmicContrast: 0.24548098701052368
purpose: []
